application:
    type: symfony2
    environment:
        php: '5.6.0'
    dependencies:
        before:
            - make init
        override:
            - make test
checks:
    php: true
filter:
    paths:
        - 'src/*'
coding_style:
    php:
        spaces:
            before_parentheses:
                function_declaration: true
                closure_definition: true
            around_operators:
                concatenation: false
        braces:
            classes_functions:
                class: new-line
                function: new-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower
tools:
    external_code_coverage:
        timeout: 120
        runs: 3
