language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script: make init; make all

script:
    - phpunit -c app --coverage-text --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
