api_rest_get_majora_entity:
    path: '/{id}'
    defaults:
        _controller: 'SirMajoraNamespaceBundle:MajoraEntityRestApi:get'
        entity: SirSdk\Component\MajoraNamespace\Model\MajoraEntity
    methods: [GET]

api_rest_cget_majora_entity:
    path: '/'
    defaults:
        _controller: 'SirMajoraNamespaceBundle:MajoraEntityRestApi:cget'
        entity: SirSdk\Component\MajoraNamespace\Model\MajoraEntity
        collection: SirSdk\Component\MajoraNamespace\Model\MajoraEntityCollection
    methods: [GET]

api_rest_post_majora_entity:
    path: '/'
    defaults:
        _controller: 'SirMajoraNamespaceBundle:MajoraEntityRestApi:post'
        entity: SirSdk\Component\MajoraNamespace\Model\MajoraEntity
    methods: [POST]

api_rest_put_majora_entity:
    path: '/{id}'
    defaults:
        _controller: 'SirMajoraNamespaceBundle:MajoraEntityRestApi:put'
    methods: [PUT]

api_rest_delete_majora_entity:
    path: '/{id}'
    defaults:
        _controller: 'SirMajoraNamespaceBundle:MajoraEntityRestApi:delete'
    methods: [DELETE]
