# ---------------------------------------
# Api
# ---------------------------------------
api_routing:
    resource: "routing_api.yml"
    prefix:   /api/

# ---------------------------------------
# localized routes
# ---------------------------------------
localized_routing:
    resource: "routing_localized.yml"
    prefix:   /{_locale}/

# ---------------------------------------
# Others
# ---------------------------------------
home_redirection:
    path:  /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%
        permanent: true
