UserBundle_internal_list:
    pattern: /
    defaults:
        _controller: 'LinkRUserBundle:AdminInternal:list'
        _format: html
    requirements:
        _format: html
        page: \d+

UserBundle_internal_timeline:
    pattern: /{Id}/{Url}/timeline
    defaults:
        _controller: 'LinkRUserBundle:Internal:timeline'
        _format: html
    requirements:
        Id: \d+
        _format: html

UserBundle_internal_edit:
    pattern: /{Id}/{Url}/edit
    defaults:
        _controller: 'LinkRUserBundle:AdminInternal:edit'
        _format: html
    requirements:
        Id: \d+
        _format: html

UserBundle_internal_new:
    pattern: /new
    defaults:
        _controller: 'LinkRUserBundle:AdminInternal:new'
        _format: html
    requirements:
        _format: html




LinkR_user_ajax_list:
    pattern: /manager/ajax-list
    defaults: { _controller: LinkRUserBundle:Internal:listAjax }
