LinkR_mission_company_list:
    pattern: /list/{page}
    defaults: { _controller: LinkRMissionBundle:Company:list }

LinkR_mission_company_new:
    pattern: /new
    defaults: { _controller: LinkRMissionBundle:Company:new }

LinkR_mission_company_edit:
    pattern: /edit/{id}
    defaults: { _controller: LinkRMissionBundle:Company:edit }

LinkR_mission_company_delete:
    pattern: /delete/{id}
    defaults: { _controller: LinkRMissionBundle:Company:delete }

LinkR_mission_company_ajax_list:
    pattern:  /ajax-list
    defaults: { _controller: LinkRMissionBundle:Company:listAjax }
