LinkR_mission_mission_list:
    pattern: /list/{consultantId}
    defaults: { _controller: LinkRMissionBundle:Mission:list }
    requirements:
        consultantId: \d+

LinkR_mission_mission_edit:
    pattern: /edit/{id}
    defaults: { _controller: LinkRMissionBundle:Mission:edit }
    requirements:
        id: \w+

LinkR_mission_mission_delete:
    pattern: /delete/{id}
    defaults: { _controller: LinkRMissionBundle:Mission:delete }
    requirements:
        id: \w+




MissionBundle_mission_admin_list:
    pattern: /
    defaults:
        _controller: LinkRMissionBundle:AdminMission:list
        _format: html
    requirements:
        _format: html

MissionBundle_mission_admin_new:
    pattern: /new.{_format}
    defaults:
        _controller: LinkRMissionBundle:AdminMission:new
        _format: json
    requirements:
        _format: json
        _method: POST

MissionBundle_mission_admin_edit:
    pattern: /{Id}/edit
    defaults:
        _controller: LinkRMissionBundle:AdminMission:edit
        _format: html
    requirements:
        id: \d+
        _format: html
