DocumentBundle_download:
    pattern: /{Id}/download
    defaults:
        _controller: "LinkRDocumentBundle:IO:download"
    requirements:
        Id: \d+

DocumentBundle_upload:
    pattern: /{Id}/upload
    defaults:
        _controller: "LinkRDocumentBundle:IO:upload"
    requirements:
        _method: POST
        _format: json
        Id: \d+
